### PR TITLE
fix: add part-attribute to svg for elements-script

### PR DESCRIPTION
**Pull request by felicia-haggqvist**
Add `part="w-icon-${name}-${size}-part"` to `<svg>` in elements-script. 

**NOTE:** This is part of implementing changes to the expandable-component in the elements-repo in order to be able to style the svg from a warp-icon that is inside a shadow-DOM. See draft-PR in elements-repo: https://github.com/warp-ds/elements/pull/107

### CODE REVIEW

**Comment by imprashast** [comment]
I would say maybe remove the crowdin file and the translation changes from this PR until we get an answer from the i18n team :)

**Comment by BalbinaK** [comment]
> I would say maybe remove the crowdin file and the translation changes from this PR until we get an answer from the i18n team :)

I can merge these as part of this Crowdin PR: https://github.com/warp-ds/icons/pull/46

**Review by BalbinaK — APPROVED** [review]
I hope this works in a server-side-rendered application, too 😄

**Review by imprashast — APPROVED** [review]
Worked fine with SSR 👍

**Pull request merged**
